"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { X } from "lucide-react"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

interface DeveloperSecurityDrawerProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export const DeveloperSecurityDrawer: React.FC<DeveloperSecurityDrawerProps> = ({ open, onOpenChange }) => {
  const [code, setCode] = React.useState(["", "", "", "", "", ""])

  const handleCodeChange = (index: number, value: string) => {
    if (value.length <= 1 && /^\d*$/.test(value)) {
      const newCode = [...code]
      newCode[index] = value
      setCode(newCode)

      // Auto-focus next input
      if (value && index < 5) {
        const nextInput = document.getElementById(`code-input-${index + 1}`)
        nextInput?.focus()
      }
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      const prevInput = document.getElementById(`code-input-${index - 1}`)
      prevInput?.focus()
    }
  }

  return (
    <AnimatePresence>
      {open && (
        <div className="fixed inset-0 z-50 flex pointer-events-none">
          {/* Backdrop */}
          <motion.div
            className="absolute inset-0 bg-black/40 backdrop-blur-sm pointer-events-auto"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => onOpenChange(false)}
          />

          {/* Drawer */}
          <motion.div
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", stiffness: 300, damping: 30 }}
            className={cn(
              "relative ml-auto w-[45%] min-w-[400px] bg-white shadow-2xl",
              "border-l border-gray-200 flex flex-col max-h-screen",
              "rounded-tl-[40px] rounded-bl-[40px] pointer-events-auto",
            )}
          >
            {/* X Close button */}
            <button
              onClick={() => onOpenChange(false)}
              className="absolute -left-20 top-6 h-10 w-10 flex items-center justify-center rounded-full bg-background shadow-md hover:bg-muted"
            >
              <X className="h-5 w-5 text-foreground" />
            </button>

            {/* Drawer Content (centered like your Bank drawer) */}
            <div className="flex-1 px-8 py-18 overflow-y-auto">
              <div className="max-w-md mx-auto space-y-6 text-center">
                <h2 className="text-lg text-gray-600 font-bold">Two-Factor Authentication</h2>

                <p className="text-sm text-gray-600">
                  You will need a <span className="font-bold">two-factor authentication app</span> to complete the
                  process, and scan this QR code with your app.
                </p>

                <div className="flex justify-center py-4">
                  <div className="w-48 h-48 flex items-center justify-center">
                    <Image
                      src="/images/qrcode.png"
                      alt="QR Code for 2FA setup"
                      width={192}
                      height={192}
                      className="w-full h-full object-contain"
                    />
                  </div>
                </div>

                <div>
                  <p className="text-sm font-medium text-gray-900 mb-1">Add code manually</p>
                  <p className="text-sm text-gray-600 mb-4">
                    Enter the 6-digit authentication code generated by your authenticator app:
                  </p>
                </div>

                {/* 6-digit code input */}
                <div className="flex justify-center gap-2">
                  {code.map((digit, index) => (
                    <input
                      key={index}
                      id={`code-input-${index}`}
                      type="text"
                      maxLength={1}
                      value={digit}
                      onChange={(e) => handleCodeChange(index, e.target.value)}
                      onKeyDown={(e) => handleKeyDown(index, e)}
                      className="w-12 h-14 text-center text-lg font-semibold border-2 border-gray-300 rounded-lg focus:border-[#2563EB] focus:outline-none bg-[#F5F5F0]"
                    />
                  ))}
                </div>

                {/* Full-width button like in your example */}
                <Button className="w-full bg-[#2563EB] text-white py-6 rounded-md font-medium hover:bg-[#1D4ED8] transition-colors mt-8">
                  Continue
                </Button>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}
