"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Drawer } from "@/components/drawer"
import Image from "next/image"

interface DeveloperSecurityDrawerProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function DeveloperSecurityDrawer({ open, onOpenChange }: DeveloperSecurityDrawerProps) {
  const [code, setCode] = useState(["", "", "", "", "", ""])

  const handleCodeChange = (index: number, value: string) => {
    if (value.length <= 1 && /^\d*$/.test(value)) {
      const newCode = [...code]
      newCode[index] = value
      setCode(newCode)

      // Auto-focus next input
      if (value && index < 5) {
        const nextInput = document.getElementById(`code-input-${index + 1}`)
        nextInput?.focus()
      }
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      const prevInput = document.getElementById(`code-input-${index - 1}`)
      prevInput?.focus()
    }
  }

  return (
    <Drawer open={open} onOpenChange={onOpenChange} title="Two-factor Authentication" subtitle="">
      <div className="space-y-6">
        <p className="text-sm text-gray-600 text-center">
          You will need a <span className="font-semibold">two-factor authentication app</span> to complete the process,
          and scan this QR code with your app.
        </p>

        <div className="flex justify-center py-4">
          <div className="w-48 h-48 flex items-center justify-center">
            <Image
              src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/icomoon-free_qrcode-uwgT0hwt1yeoYggrMqlvZoJlwwaKFH.png"
              alt="QR Code for 2FA setup"
              width={192}
              height={192}
              className="w-full h-full object-contain"
            />
          </div>
        </div>

        <div className="text-center">
          <p className="text-sm font-medium text-gray-900 mb-1">Add code manually</p>
          <p className="text-sm text-gray-600 mb-4">
            Enter the 6-digit authentication code generated by your authenticator app:
          </p>
        </div>

        {/* 6-digit code input */}
        <div className="flex justify-center gap-2">
          {code.map((digit, index) => (
            <input
              key={index}
              id={`code-input-${index}`}
              type="text"
              maxLength={1}
              value={digit}
              onChange={(e) => handleCodeChange(index, e.target.value)}
              onKeyDown={(e) => handleKeyDown(index, e)}
              className="w-12 h-14 text-center text-lg font-semibold border-2 border-gray-300 rounded-lg focus:border-[#9A813F] focus:outline-none bg-[#F5F5F0]"
            />
          ))}
        </div>

        <Button className="w-full bg-black text-white hover:bg-gray-800">Continue</Button>
      </div>
    </Drawer>
  )
}
