"use client"

import { Button } from "@/components/ui/button"
import { Drawer } from "@/components/drawer"

interface TwoFactorDrawerProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function TwoFactorDrawer({ open, onOpenChange }: TwoFactorDrawerProps) {
  return (
    <Drawer open={open} onOpenChange={onOpenChange} title="Two-factor Authentication" subtitle="">
      <div className="space-y-6">
        <p className="text-sm text-gray-600 text-center">
          You will need a <span className="font-medium">two-factor authentication app</span> to complete the process,
          and scan this QR code with your app.
        </p>

        <div className="w-32 h-32 bg-[#9A813F] mx-auto rounded-lg flex items-center justify-center">
          <div className="w-28 h-28 bg-white rounded grid grid-cols-3 gap-1 p-2">
            {Array.from({ length: 9 }).map((_, i) => (
              <div key={i} className={`${i % 2 === 0 ? "bg-[#9A813F]" : "bg-white"}`} />
            ))}
          </div>
        </div>

        <button className="text-sm text-center w-full font-medium">Add code manually</button>

        <div className="space-y-3">
          <p className="text-sm text-gray-600 text-center">
            Enter the 6-digit authentication code generated by your authenticator app:
          </p>
          <div className="flex gap-2 justify-center">
            {Array.from({ length: 5 }).map((_, i) => (
              <input
                key={i}
                type="text"
                maxLength={1}
                className="w-12 h-12 text-center border border-gray-300 rounded-md text-lg font-medium focus:border-[#9A813F] focus:ring-1 focus:ring-[#9A813F]"
              />
            ))}
          </div>
        </div>

        <Button className="w-full bg-black text-white hover:bg-gray-800">Continue</Button>
      </div>
    </Drawer>
  )
}
